# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'Cookie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Cookie
  pod 'AFNetworking', '~> 2.5.1'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MMDrawerController', '~> 0.5.7'

end
